/**
 * Generates opensearch_dashboards.yml from SQLite-persisted settings.
 * Called on: first run, settings change, OSD upgrade.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { OSD_DIR } from './downloader.js';

export interface OsdSettings {
  'server.host'?: string;
  'server.port'?: number;
  'server.basePath'?: string;
  'opensearch.hosts'?: string[];
  'opensearch.ssl.verificationMode'?: 'full' | 'certificate' | 'none';
  'opensearch.username'?: string;
  'opensearch.password'?: string;
  'data_source.enabled'?: boolean;
  'logging.dest'?: string;
  [key: string]: unknown;
}

const DEFAULTS: OsdSettings = {
  'server.host': '127.0.0.1',
  'server.port': 5601,
  'server.basePath': '',
  'opensearch.hosts': [],
  'opensearch.ssl.verificationMode': 'none',
  'data_source.enabled': true,
};

export function generateConfig(
  settings: OsdSettings,
  plugins: string[] = [],
): string {
  const merged = { ...DEFAULTS, ...settings };
  const lines: string[] = ['# Auto-generated by OSD Desktop — do not edit manually', ''];

  for (const [key, value] of Object.entries(merged)) {
    if (value === undefined) continue;
    lines.push(`${key}: ${formatYamlValue(value)}`);
  }

  // Disable plugins not in the tracked list
  if (plugins.length > 0) {
    lines.push('', '# Managed plugins');
  }

  return lines.join('\n') + '\n';
}

export function writeConfig(settings: OsdSettings, plugins: string[] = []): string {
  const configDir = join(OSD_DIR, 'config');
  mkdirSync(configDir, { recursive: true });
  const configPath = join(configDir, 'opensearch_dashboards.yml');
  const content = generateConfig(settings, plugins);
  writeFileSync(configPath, content, 'utf8');
  return configPath;
}

function formatYamlValue(value: unknown): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[${value.map((v) => `"${v}"`).join(', ')}]`;
  }
  if (typeof value === 'string') return `"${value}"`;
  return String(value);
}
